"""Update treatment model

Revision ID: a328f68c9e0b
Revises: 9a60f388e84f
Create Date: 2025-10-26 12:49:16.172849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a328f68c9e0b'
down_revision = '9a60f388e84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organic_status', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cost_estimate', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_column('cost_estimate')
        batch_op.drop_column('organic_status')

    # ### end Alembic commands ###
