"""Update disease model

Revision ID: 9a60f388e84f
Revises: 6f7cbc3a7ba7
Create Date: 2025-10-26 12:48:50.323049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a60f388e84f'
down_revision = '6f7cbc3a7ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cause', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_model_accuracy', sa.Float(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('severity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('ai_model_accuracy')
        batch_op.drop_column('cause')
        batch_op.drop_column('symptoms')

    # ### end Alembic commands ###
