"""Add priority_rank to DiseaseTreatment

Revision ID: b09b31fcf343
Revises: a328f68c9e0b
Create Date: 2025-10-26 12:49:44.616014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09b31fcf343'
down_revision = 'a328f68c9e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_treatments', schema=None) as batch_op:
        batch_op.drop_column('priority_rank')

    # ### end Alembic commands ###
